// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openconfig.proto

/*
Package openconfig is a generated protocol buffer package.

It is generated from these files:
	openconfig.proto

It has these top-level messages:
	Path
	PathElem
	ExecRequest
	ExecReply
	RegisterRequest
	RegisterReply
	RegisterModuleRequest
	RegisterModuleReply
	ExecModuleRequest
	ExecModuleReply
	SubscribeRequest
	ConfigRequest
	ConfigReply
	ShowRequest
	ShowReply
*/
package openconfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Command message type.
type ExecType int32

const (
	ExecType_EXEC                    ExecType = 0
	ExecType_COMPLETE                ExecType = 1
	ExecType_COMPLETE_TRAILING_SPACE ExecType = 2
	ExecType_COMPLETE_FIRST_COMMANDS ExecType = 3
	ExecType_COMPLETE_DYNAMIC        ExecType = 4
)

var ExecType_name = map[int32]string{
	0: "EXEC",
	1: "COMPLETE",
	2: "COMPLETE_TRAILING_SPACE",
	3: "COMPLETE_FIRST_COMMANDS",
	4: "COMPLETE_DYNAMIC",
}
var ExecType_value = map[string]int32{
	"EXEC":                    0,
	"COMPLETE":                1,
	"COMPLETE_TRAILING_SPACE": 2,
	"COMPLETE_FIRST_COMMANDS": 3,
	"COMPLETE_DYNAMIC":        4,
}

func (x ExecType) String() string {
	return proto.EnumName(ExecType_name, int32(x))
}
func (ExecType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Command reply format type.
type ExecConentType int32

const (
	ExecConentType_CONTENT_TEXT ExecConentType = 0
	ExecConentType_CONTENT_JSON ExecConentType = 1
)

var ExecConentType_name = map[int32]string{
	0: "CONTENT_TEXT",
	1: "CONTENT_JSON",
}
var ExecConentType_value = map[string]int32{
	"CONTENT_TEXT": 0,
	"CONTENT_JSON": 1,
}

func (x ExecConentType) String() string {
	return proto.EnumName(ExecConentType_name, int32(x))
}
func (ExecConentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Command exec code.
type ExecCode int32

const (
	ExecCode_SUCCESS       ExecCode = 0
	ExecCode_NOMATCH       ExecCode = 1
	ExecCode_INCOMPLETE    ExecCode = 2
	ExecCode_AMBIGUOUS     ExecCode = 3
	ExecCode_SHOW          ExecCode = 4
	ExecCode_REDIRECT      ExecCode = 5
	ExecCode_REDIRECT_SHOW ExecCode = 6
)

var ExecCode_name = map[int32]string{
	0: "SUCCESS",
	1: "NOMATCH",
	2: "INCOMPLETE",
	3: "AMBIGUOUS",
	4: "SHOW",
	5: "REDIRECT",
	6: "REDIRECT_SHOW",
}
var ExecCode_value = map[string]int32{
	"SUCCESS":       0,
	"NOMATCH":       1,
	"INCOMPLETE":    2,
	"AMBIGUOUS":     3,
	"SHOW":          4,
	"REDIRECT":      5,
	"REDIRECT_SHOW": 6,
}

func (x ExecCode) String() string {
	return proto.EnumName(ExecCode_name, int32(x))
}
func (ExecCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Configuration service
type ConfigType int32

const (
	ConfigType_SET               ConfigType = 0
	ConfigType_DELETE            ConfigType = 1
	ConfigType_VALIDATE_START    ConfigType = 2
	ConfigType_VALIDATE_END      ConfigType = 3
	ConfigType_VALIDATE_SUCCESS  ConfigType = 4
	ConfigType_VALIDATE_FAILED   ConfigType = 5
	ConfigType_COMMIT_START      ConfigType = 6
	ConfigType_COMMIT_END        ConfigType = 7
	ConfigType_SUBSCRIBE         ConfigType = 8
	ConfigType_SUBSCRIBE_MULTI   ConfigType = 9
	ConfigType_SUBSCRIBE_REQUEST ConfigType = 10
	ConfigType_JSON_CONFIG       ConfigType = 11
)

var ConfigType_name = map[int32]string{
	0:  "SET",
	1:  "DELETE",
	2:  "VALIDATE_START",
	3:  "VALIDATE_END",
	4:  "VALIDATE_SUCCESS",
	5:  "VALIDATE_FAILED",
	6:  "COMMIT_START",
	7:  "COMMIT_END",
	8:  "SUBSCRIBE",
	9:  "SUBSCRIBE_MULTI",
	10: "SUBSCRIBE_REQUEST",
	11: "JSON_CONFIG",
}
var ConfigType_value = map[string]int32{
	"SET":               0,
	"DELETE":            1,
	"VALIDATE_START":    2,
	"VALIDATE_END":      3,
	"VALIDATE_SUCCESS":  4,
	"VALIDATE_FAILED":   5,
	"COMMIT_START":      6,
	"COMMIT_END":        7,
	"SUBSCRIBE":         8,
	"SUBSCRIBE_MULTI":   9,
	"SUBSCRIBE_REQUEST": 10,
	"JSON_CONFIG":       11,
}

func (x ConfigType) String() string {
	return proto.EnumName(ConfigType_name, int32(x))
}
func (ConfigType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Subscribe type.
type SubscribeType int32

const (
	SubscribeType_COMMAND SubscribeType = 0
	SubscribeType_JSON    SubscribeType = 1
)

var SubscribeType_name = map[int32]string{
	0: "COMMAND",
	1: "JSON",
}
var SubscribeType_value = map[string]int32{
	"COMMAND": 0,
	"JSON":    1,
}

func (x SubscribeType) String() string {
	return proto.EnumName(SubscribeType_name, int32(x))
}
func (SubscribeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Path encodes a data tree path as a series of repeated strings, with
// each element of the path representing a data tree node name and the
// associated attributes.
// Reference: gNMI Specification Section 2.2.2.
type Path struct {
	// Elements of the path are no longer encoded as a string, but rather within
	// the elem field as a PathElem message.
	Element []string    `protobuf:"bytes,1,rep,name=element" json:"element,omitempty"`
	Origin  string      `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
	Elem    []*PathElem `protobuf:"bytes,3,rep,name=elem" json:"elem,omitempty"`
	Target  string      `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Path) GetElement() []string {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *Path) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Path) GetElem() []*PathElem {
	if m != nil {
		return m.Elem
	}
	return nil
}

func (m *Path) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// PathElem encodes an element of a gNMI path, along ith any attributes (keys)
// that may be associated with it.
// Reference: gNMI Specification Section 2.2.2.
type PathElem struct {
	Name string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key  map[string]string `protobuf:"bytes,2,rep,name=key" json:"key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PathElem) Reset()                    { *m = PathElem{} }
func (m *PathElem) String() string            { return proto.CompactTextString(m) }
func (*PathElem) ProtoMessage()               {}
func (*PathElem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PathElem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PathElem) GetKey() map[string]string {
	if m != nil {
		return m.Key
	}
	return nil
}

// The request message containing user input string.
type ExecRequest struct {
	Type      ExecType       `protobuf:"varint,1,opt,name=type,enum=openconfig.ExecType" json:"type,omitempty"`
	Mode      string         `protobuf:"bytes,2,opt,name=mode" json:"mode,omitempty"`
	Privilege uint32         `protobuf:"varint,3,opt,name=privilege" json:"privilege,omitempty"`
	Line      string         `protobuf:"bytes,4,opt,name=line" json:"line,omitempty"`
	Commands  []string       `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	Args      []string       `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	Content   ExecConentType `protobuf:"varint,7,opt,name=content,enum=openconfig.ExecConentType" json:"content,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExecRequest) GetType() ExecType {
	if m != nil {
		return m.Type
	}
	return ExecType_EXEC
}

func (m *ExecRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ExecRequest) GetPrivilege() uint32 {
	if m != nil {
		return m.Privilege
	}
	return 0
}

func (m *ExecRequest) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *ExecRequest) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *ExecRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecRequest) GetContent() ExecConentType {
	if m != nil {
		return m.Content
	}
	return ExecConentType_CONTENT_TEXT
}

// The response message containing the completion with help.
type ExecReply struct {
	Code       ExecCode `protobuf:"varint,1,opt,name=code,enum=openconfig.ExecCode" json:"code,omitempty"`
	Lines      string   `protobuf:"bytes,2,opt,name=lines" json:"lines,omitempty"`
	Port       uint32   `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Candidates []string `protobuf:"bytes,4,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *ExecReply) Reset()                    { *m = ExecReply{} }
func (m *ExecReply) String() string            { return proto.CompactTextString(m) }
func (*ExecReply) ProtoMessage()               {}
func (*ExecReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExecReply) GetCode() ExecCode {
	if m != nil {
		return m.Code
	}
	return ExecCode_SUCCESS
}

func (m *ExecReply) GetLines() string {
	if m != nil {
		return m.Lines
	}
	return ""
}

func (m *ExecReply) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ExecReply) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

// The request message for command definition.
type RegisterRequest struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Module    string   `protobuf:"bytes,2,opt,name=module" json:"module,omitempty"`
	Mode      string   `protobuf:"bytes,3,opt,name=mode" json:"mode,omitempty"`
	Line      string   `protobuf:"bytes,4,opt,name=line" json:"line,omitempty"`
	Privilege uint32   `protobuf:"varint,5,opt,name=privilege" json:"privilege,omitempty"`
	Helps     []string `protobuf:"bytes,6,rep,name=helps" json:"helps,omitempty"`
	Code      ExecCode `protobuf:"varint,7,opt,name=code,enum=openconfig.ExecCode" json:"code,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *RegisterRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *RegisterRequest) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *RegisterRequest) GetPrivilege() uint32 {
	if m != nil {
		return m.Privilege
	}
	return 0
}

func (m *RegisterRequest) GetHelps() []string {
	if m != nil {
		return m.Helps
	}
	return nil
}

func (m *RegisterRequest) GetCode() ExecCode {
	if m != nil {
		return m.Code
	}
	return ExecCode_SUCCESS
}

// The response message for callback ID.
type RegisterReply struct {
	Callbackid int32 `protobuf:"varint,1,opt,name=callbackid" json:"callbackid,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegisterReply) GetCallbackid() int32 {
	if m != nil {
		return m.Callbackid
	}
	return 0
}

// The request message mode information.
type RegisterModuleRequest struct {
	Module string `protobuf:"bytes,1,opt,name=module" json:"module,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *RegisterModuleRequest) Reset()                    { *m = RegisterModuleRequest{} }
func (m *RegisterModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterModuleRequest) ProtoMessage()               {}
func (*RegisterModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RegisterModuleRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *RegisterModuleRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

// The response message containing the callbackID for the mode change.
type RegisterModuleReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *RegisterModuleReply) Reset()                    { *m = RegisterModuleReply{} }
func (m *RegisterModuleReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterModuleReply) ProtoMessage()               {}
func (*RegisterModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RegisterModuleReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// The request message mode information.
type ExecModuleRequest struct {
	Callbackid int32    `protobuf:"varint,1,opt,name=callbackid" json:"callbackid,omitempty"`
	Args       []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *ExecModuleRequest) Reset()                    { *m = ExecModuleRequest{} }
func (m *ExecModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecModuleRequest) ProtoMessage()               {}
func (*ExecModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ExecModuleRequest) GetCallbackid() int32 {
	if m != nil {
		return m.Callbackid
	}
	return 0
}

func (m *ExecModuleRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// The response message containing the callbackID for the mode change.
type ExecModuleReply struct {
	Result int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Line   string `protobuf:"bytes,2,opt,name=line" json:"line,omitempty"`
}

func (m *ExecModuleReply) Reset()                    { *m = ExecModuleReply{} }
func (m *ExecModuleReply) String() string            { return proto.CompactTextString(m) }
func (*ExecModuleReply) ProtoMessage()               {}
func (*ExecModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ExecModuleReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ExecModuleReply) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type SubscribeRequest struct {
	Type SubscribeType `protobuf:"varint,1,opt,name=type,enum=openconfig.SubscribeType" json:"type,omitempty"`
	Path string        `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SubscribeRequest) GetType() SubscribeType {
	if m != nil {
		return m.Type
	}
	return SubscribeType_COMMAND
}

func (m *SubscribeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ConfigRequest struct {
	Type      ConfigType          `protobuf:"varint,1,opt,name=type,enum=openconfig.ConfigType" json:"type,omitempty"`
	Module    string              `protobuf:"bytes,2,opt,name=module" json:"module,omitempty"`
	Port      uint32              `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Subtype   SubscribeType       `protobuf:"varint,4,opt,name=subtype,enum=openconfig.SubscribeType" json:"subtype,omitempty"`
	Path      []string            `protobuf:"bytes,5,rep,name=path" json:"path,omitempty"`
	Subscribe []*SubscribeRequest `protobuf:"bytes,6,rep,name=subscribe" json:"subscribe,omitempty"`
}

func (m *ConfigRequest) Reset()                    { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()               {}
func (*ConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ConfigRequest) GetType() ConfigType {
	if m != nil {
		return m.Type
	}
	return ConfigType_SET
}

func (m *ConfigRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ConfigRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConfigRequest) GetSubtype() SubscribeType {
	if m != nil {
		return m.Subtype
	}
	return SubscribeType_COMMAND
}

func (m *ConfigRequest) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ConfigRequest) GetSubscribe() []*SubscribeRequest {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

type ConfigReply struct {
	Result int32      `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Type   ConfigType `protobuf:"varint,2,opt,name=type,enum=openconfig.ConfigType" json:"type,omitempty"`
	Path   []string   `protobuf:"bytes,3,rep,name=path" json:"path,omitempty"`
	Json   string     `protobuf:"bytes,4,opt,name=json" json:"json,omitempty"`
}

func (m *ConfigReply) Reset()                    { *m = ConfigReply{} }
func (m *ConfigReply) String() string            { return proto.CompactTextString(m) }
func (*ConfigReply) ProtoMessage()               {}
func (*ConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ConfigReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ConfigReply) GetType() ConfigType {
	if m != nil {
		return m.Type
	}
	return ConfigType_SET
}

func (m *ConfigReply) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ConfigReply) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

// Show service.
type ShowRequest struct {
	Line string `protobuf:"bytes,1,opt,name=line" json:"line,omitempty"`
	Json bool   `protobuf:"varint,2,opt,name=json" json:"json,omitempty"`
}

func (m *ShowRequest) Reset()                    { *m = ShowRequest{} }
func (m *ShowRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()               {}
func (*ShowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ShowRequest) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *ShowRequest) GetJson() bool {
	if m != nil {
		return m.Json
	}
	return false
}

type ShowReply struct {
	Str string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
}

func (m *ShowReply) Reset()                    { *m = ShowReply{} }
func (m *ShowReply) String() string            { return proto.CompactTextString(m) }
func (*ShowReply) ProtoMessage()               {}
func (*ShowReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ShowReply) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*Path)(nil), "openconfig.Path")
	proto.RegisterType((*PathElem)(nil), "openconfig.PathElem")
	proto.RegisterType((*ExecRequest)(nil), "openconfig.ExecRequest")
	proto.RegisterType((*ExecReply)(nil), "openconfig.ExecReply")
	proto.RegisterType((*RegisterRequest)(nil), "openconfig.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "openconfig.RegisterReply")
	proto.RegisterType((*RegisterModuleRequest)(nil), "openconfig.RegisterModuleRequest")
	proto.RegisterType((*RegisterModuleReply)(nil), "openconfig.RegisterModuleReply")
	proto.RegisterType((*ExecModuleRequest)(nil), "openconfig.ExecModuleRequest")
	proto.RegisterType((*ExecModuleReply)(nil), "openconfig.ExecModuleReply")
	proto.RegisterType((*SubscribeRequest)(nil), "openconfig.SubscribeRequest")
	proto.RegisterType((*ConfigRequest)(nil), "openconfig.ConfigRequest")
	proto.RegisterType((*ConfigReply)(nil), "openconfig.ConfigReply")
	proto.RegisterType((*ShowRequest)(nil), "openconfig.ShowRequest")
	proto.RegisterType((*ShowReply)(nil), "openconfig.ShowReply")
	proto.RegisterEnum("openconfig.ExecType", ExecType_name, ExecType_value)
	proto.RegisterEnum("openconfig.ExecConentType", ExecConentType_name, ExecConentType_value)
	proto.RegisterEnum("openconfig.ExecCode", ExecCode_name, ExecCode_value)
	proto.RegisterEnum("openconfig.ConfigType", ConfigType_name, ConfigType_value)
	proto.RegisterEnum("openconfig.SubscribeType", SubscribeType_name, SubscribeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Exec service

type ExecClient interface {
	DoExec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecReply, error)
}

type execClient struct {
	cc *grpc.ClientConn
}

func NewExecClient(cc *grpc.ClientConn) ExecClient {
	return &execClient{cc}
}

func (c *execClient) DoExec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecReply, error) {
	out := new(ExecReply)
	err := grpc.Invoke(ctx, "/openconfig.Exec/DoExec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Exec service

type ExecServer interface {
	DoExec(context.Context, *ExecRequest) (*ExecReply, error)
}

func RegisterExecServer(s *grpc.Server, srv ExecServer) {
	s.RegisterService(&_Exec_serviceDesc, srv)
}

func _Exec_DoExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServer).DoExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.Exec/DoExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServer).DoExec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Exec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.Exec",
	HandlerType: (*ExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoExec",
			Handler:    _Exec_DoExec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openconfig.proto",
}

// Client API for Register service

type RegisterClient interface {
	DoRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	DoRegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleReply, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) DoRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/openconfig.Register/DoRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) DoRegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleReply, error) {
	out := new(RegisterModuleReply)
	err := grpc.Invoke(ctx, "/openconfig.Register/DoRegisterModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Register service

type RegisterServer interface {
	DoRegister(context.Context, *RegisterRequest) (*RegisterReply, error)
	DoRegisterModule(context.Context, *RegisterModuleRequest) (*RegisterModuleReply, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_DoRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).DoRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.Register/DoRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).DoRegister(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_DoRegisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).DoRegisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.Register/DoRegisterModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).DoRegisterModule(ctx, req.(*RegisterModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRegister",
			Handler:    _Register_DoRegister_Handler,
		},
		{
			MethodName: "DoRegisterModule",
			Handler:    _Register_DoRegisterModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openconfig.proto",
}

// Client API for ExecModule service

type ExecModuleClient interface {
	DoExecModule(ctx context.Context, in *ExecModuleRequest, opts ...grpc.CallOption) (*ExecModuleReply, error)
}

type execModuleClient struct {
	cc *grpc.ClientConn
}

func NewExecModuleClient(cc *grpc.ClientConn) ExecModuleClient {
	return &execModuleClient{cc}
}

func (c *execModuleClient) DoExecModule(ctx context.Context, in *ExecModuleRequest, opts ...grpc.CallOption) (*ExecModuleReply, error) {
	out := new(ExecModuleReply)
	err := grpc.Invoke(ctx, "/openconfig.ExecModule/DoExecModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExecModule service

type ExecModuleServer interface {
	DoExecModule(context.Context, *ExecModuleRequest) (*ExecModuleReply, error)
}

func RegisterExecModuleServer(s *grpc.Server, srv ExecModuleServer) {
	s.RegisterService(&_ExecModule_serviceDesc, srv)
}

func _ExecModule_DoExecModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecModuleServer).DoExecModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openconfig.ExecModule/DoExecModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecModuleServer).DoExecModule(ctx, req.(*ExecModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecModule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.ExecModule",
	HandlerType: (*ExecModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoExecModule",
			Handler:    _ExecModule_DoExecModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openconfig.proto",
}

// Client API for Config service

type ConfigClient interface {
	DoConfig(ctx context.Context, opts ...grpc.CallOption) (Config_DoConfigClient, error)
}

type configClient struct {
	cc *grpc.ClientConn
}

func NewConfigClient(cc *grpc.ClientConn) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) DoConfig(ctx context.Context, opts ...grpc.CallOption) (Config_DoConfigClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Config_serviceDesc.Streams[0], c.cc, "/openconfig.Config/DoConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &configDoConfigClient{stream}
	return x, nil
}

type Config_DoConfigClient interface {
	Send(*ConfigRequest) error
	Recv() (*ConfigReply, error)
	grpc.ClientStream
}

type configDoConfigClient struct {
	grpc.ClientStream
}

func (x *configDoConfigClient) Send(m *ConfigRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *configDoConfigClient) Recv() (*ConfigReply, error) {
	m := new(ConfigReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Config service

type ConfigServer interface {
	DoConfig(Config_DoConfigServer) error
}

func RegisterConfigServer(s *grpc.Server, srv ConfigServer) {
	s.RegisterService(&_Config_serviceDesc, srv)
}

func _Config_DoConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigServer).DoConfig(&configDoConfigServer{stream})
}

type Config_DoConfigServer interface {
	Send(*ConfigReply) error
	Recv() (*ConfigRequest, error)
	grpc.ServerStream
}

type configDoConfigServer struct {
	grpc.ServerStream
}

func (x *configDoConfigServer) Send(m *ConfigReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *configDoConfigServer) Recv() (*ConfigRequest, error) {
	m := new(ConfigRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Config_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoConfig",
			Handler:       _Config_DoConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "openconfig.proto",
}

// Client API for Show service

type ShowClient interface {
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (Show_ShowClient, error)
}

type showClient struct {
	cc *grpc.ClientConn
}

func NewShowClient(cc *grpc.ClientConn) ShowClient {
	return &showClient{cc}
}

func (c *showClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (Show_ShowClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Show_serviceDesc.Streams[0], c.cc, "/openconfig.Show/Show", opts...)
	if err != nil {
		return nil, err
	}
	x := &showShowClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Show_ShowClient interface {
	Recv() (*ShowReply, error)
	grpc.ClientStream
}

type showShowClient struct {
	grpc.ClientStream
}

func (x *showShowClient) Recv() (*ShowReply, error) {
	m := new(ShowReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Show service

type ShowServer interface {
	Show(*ShowRequest, Show_ShowServer) error
}

func RegisterShowServer(s *grpc.Server, srv ShowServer) {
	s.RegisterService(&_Show_serviceDesc, srv)
}

func _Show_Show_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShowServer).Show(m, &showShowServer{stream})
}

type Show_ShowServer interface {
	Send(*ShowReply) error
	grpc.ServerStream
}

type showShowServer struct {
	grpc.ServerStream
}

func (x *showShowServer) Send(m *ShowReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Show_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openconfig.Show",
	HandlerType: (*ShowServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Show",
			Handler:       _Show_Show_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "openconfig.proto",
}

func init() { proto.RegisterFile("openconfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcb, 0x72, 0xe3, 0x44,
	0x14, 0xb5, 0x6c, 0xf9, 0x75, 0x3d, 0x4e, 0x3a, 0x3d, 0x79, 0x38, 0x4e, 0x02, 0x41, 0x0b, 0xca,
	0xe5, 0xaa, 0xc9, 0x4c, 0x65, 0x06, 0x8a, 0x4a, 0x15, 0x0b, 0x47, 0x56, 0x32, 0x02, 0x5b, 0x0e,
	0x92, 0x0c, 0x81, 0x8d, 0x4b, 0xb1, 0x1b, 0xc7, 0x8c, 0x2c, 0x19, 0x49, 0x1e, 0xf0, 0x06, 0x96,
	0xfc, 0x0c, 0x7f, 0xc1, 0x8f, 0x50, 0xc5, 0x96, 0x8f, 0xa0, 0xba, 0xa5, 0xd6, 0xc3, 0xf1, 0x24,
	0xac, 0xd2, 0xf7, 0xea, 0xf6, 0xe9, 0x73, 0xce, 0xed, 0xbe, 0x31, 0x20, 0x77, 0x41, 0x9c, 0xb1,
	0xeb, 0xfc, 0x38, 0x9b, 0x9e, 0x2d, 0x3c, 0x37, 0x70, 0x31, 0x24, 0x19, 0xe9, 0x37, 0x10, 0x6f,
	0xac, 0xe0, 0x1e, 0x1f, 0x43, 0x99, 0xd8, 0x64, 0x4e, 0x9c, 0xa0, 0x21, 0x9c, 0x16, 0x5a, 0xd5,
	0xcb, 0x7c, 0x43, 0xd0, 0x79, 0x0a, 0xef, 0x43, 0xc9, 0xf5, 0x66, 0xd3, 0x99, 0xd3, 0xc8, 0x9f,
	0x0a, 0xad, 0xaa, 0x1e, 0x45, 0xb8, 0x05, 0x22, 0x2d, 0x69, 0x14, 0x4e, 0x0b, 0xad, 0xda, 0xf9,
	0xee, 0x59, 0xea, 0x28, 0x8a, 0xaa, 0xd8, 0x64, 0xae, 0xb3, 0x0a, 0x8a, 0x10, 0x58, 0xde, 0x94,
	0x04, 0x0d, 0x31, 0x44, 0x08, 0x23, 0xe9, 0x0f, 0x01, 0x2a, 0xbc, 0x14, 0x63, 0x10, 0x1d, 0x6b,
	0x4e, 0x1a, 0x02, 0x2b, 0x61, 0x6b, 0xfc, 0x12, 0x0a, 0xef, 0xc8, 0xaa, 0x91, 0x67, 0x27, 0x9c,
	0x6c, 0x3a, 0xe1, 0xec, 0x6b, 0xb2, 0x52, 0x9c, 0xc0, 0x5b, 0xe9, 0xb4, 0xb2, 0xf9, 0x39, 0x54,
	0x78, 0x02, 0xa3, 0x70, 0x73, 0x88, 0x47, 0x97, 0x78, 0x17, 0x8a, 0xef, 0x2d, 0x7b, 0x49, 0x22,
	0x21, 0x61, 0x70, 0x91, 0xff, 0x42, 0x90, 0xfe, 0x11, 0xa0, 0xa6, 0xfc, 0x4a, 0xc6, 0x3a, 0xf9,
	0x79, 0x49, 0xfc, 0x80, 0x6a, 0x0b, 0x56, 0x8b, 0x90, 0xcc, 0x56, 0x56, 0x1b, 0x2d, 0x33, 0x57,
	0x0b, 0xa2, 0xb3, 0x0a, 0x4a, 0x7b, 0xee, 0x4e, 0x38, 0x24, 0x5b, 0xe3, 0x63, 0xa8, 0x2e, 0xbc,
	0xd9, 0xfb, 0x99, 0x4d, 0xa6, 0xa4, 0x51, 0x38, 0x15, 0x5a, 0x75, 0x3d, 0x49, 0xd0, 0x1d, 0xf6,
	0xcc, 0x21, 0x91, 0x17, 0x6c, 0x8d, 0x9b, 0x50, 0x19, 0xbb, 0xf3, 0xb9, 0xe5, 0x4c, 0xfc, 0x46,
	0x91, 0xb6, 0x40, 0x8f, 0x63, 0x5a, 0x6f, 0x79, 0x53, 0xbf, 0x51, 0x62, 0x79, 0xb6, 0xc6, 0x6f,
	0xa0, 0x3c, 0x76, 0x9d, 0x80, 0x76, 0xac, 0xcc, 0x28, 0x36, 0xd7, 0x29, 0xca, 0xae, 0x43, 0x9c,
	0x80, 0x11, 0xe5, 0xa5, 0xd2, 0xef, 0x50, 0x0d, 0x45, 0x2e, 0xec, 0x15, 0x95, 0x38, 0xa6, 0xc4,
	0x3f, 0x20, 0x51, 0x76, 0x27, 0x44, 0x67, 0x15, 0xd4, 0x36, 0x4a, 0xd2, 0xe7, 0xb6, 0xb1, 0x80,
	0xd2, 0x5a, 0xb8, 0x5e, 0x10, 0xe9, 0x63, 0x6b, 0xfc, 0x11, 0xc0, 0xd8, 0x72, 0x26, 0xb3, 0x89,
	0x15, 0x10, 0xbf, 0x21, 0x32, 0xc2, 0xa9, 0x8c, 0xf4, 0x97, 0x00, 0xdb, 0x3a, 0x99, 0xce, 0xfc,
	0x80, 0x78, 0xdc, 0xea, 0x4d, 0x7d, 0xdf, 0x87, 0xd2, 0xdc, 0x9d, 0x2c, 0x6d, 0x6e, 0x6b, 0x14,
	0xc5, 0x66, 0x17, 0x52, 0x66, 0x6f, 0xb2, 0x33, 0xd3, 0x80, 0xe2, 0x7a, 0x03, 0x76, 0xa1, 0x78,
	0x4f, 0xec, 0x05, 0x77, 0x34, 0x0c, 0x62, 0x3f, 0xca, 0x4f, 0xf9, 0x21, 0xbd, 0x84, 0x7a, 0x22,
	0x82, 0x5a, 0xc9, 0x64, 0xdb, 0xf6, 0x9d, 0x35, 0x7e, 0x37, 0x9b, 0x30, 0x21, 0x45, 0x3d, 0x95,
	0x91, 0x64, 0xd8, 0xe3, 0x1b, 0xfa, 0x4c, 0x08, 0xd7, 0x9e, 0xe8, 0x14, 0xd6, 0x75, 0x32, 0x6f,
	0xa3, 0x4b, 0x45, 0xd7, 0xd2, 0x0b, 0x78, 0xbe, 0x0e, 0x42, 0xcf, 0xde, 0x87, 0x92, 0x47, 0xfc,
	0xa5, 0x1d, 0x44, 0xe7, 0x46, 0x91, 0x74, 0x0d, 0x3b, 0x94, 0x76, 0xf6, 0xbc, 0x27, 0x88, 0xc6,
	0x57, 0x2d, 0x9f, 0x5c, 0x35, 0xe9, 0x4b, 0xd8, 0x4e, 0x03, 0x3d, 0x72, 0x66, 0xdc, 0x8a, 0x7c,
	0xd2, 0x0a, 0x69, 0x08, 0xc8, 0x58, 0xde, 0xf9, 0x63, 0x6f, 0x76, 0x17, 0xd3, 0x78, 0x91, 0x79,
	0x5d, 0x87, 0x69, 0xab, 0xe3, 0xda, 0xec, 0x13, 0x5b, 0x58, 0xc1, 0x7d, 0xec, 0x86, 0x15, 0xdc,
	0x4b, 0xff, 0x0a, 0x50, 0x97, 0xd9, 0x16, 0x0e, 0xda, 0xce, 0x80, 0xee, 0xa7, 0x41, 0xc3, 0xc2,
	0x14, 0xe2, 0x23, 0xf7, 0xeb, 0xc1, 0x9d, 0x7e, 0x0d, 0x65, 0x7f, 0x79, 0xc7, 0xa0, 0xc5, 0xa7,
	0xf8, 0xf2, 0xca, 0x98, 0x72, 0xf8, 0x96, 0xd9, 0x1a, 0x5f, 0x40, 0xd5, 0xe7, 0xd5, 0xec, 0xea,
	0xd5, 0xce, 0x8f, 0x37, 0x42, 0x45, 0x8a, 0xf4, 0xa4, 0x5c, 0x5a, 0x41, 0x8d, 0xab, 0x7d, 0xac,
	0x01, 0xdc, 0x83, 0xfc, 0xff, 0xf0, 0x80, 0x53, 0x2c, 0xa4, 0x28, 0x62, 0x10, 0x7f, 0xf2, 0x5d,
	0x87, 0xbf, 0x25, 0xba, 0x96, 0x3e, 0x83, 0x9a, 0x71, 0xef, 0xfe, 0x92, 0x7a, 0xae, 0xac, 0xc7,
	0x42, 0xea, 0xb9, 0xf1, 0x6d, 0xf4, 0xd8, 0x4a, 0xb4, 0xed, 0x04, 0xaa, 0xe1, 0x36, 0xca, 0x17,
	0x41, 0xc1, 0x0f, 0x3c, 0x3e, 0x8a, 0xfd, 0xc0, 0x6b, 0x7b, 0x50, 0xe1, 0x83, 0x14, 0x57, 0x40,
	0x54, 0x6e, 0x15, 0x19, 0xe5, 0xf0, 0x33, 0xa8, 0xc8, 0x83, 0xfe, 0x4d, 0x4f, 0x31, 0x15, 0x24,
	0xe0, 0x23, 0x38, 0xe0, 0xd1, 0xc8, 0xd4, 0x3b, 0x6a, 0x4f, 0xd5, 0xae, 0x47, 0xc6, 0x4d, 0x47,
	0x56, 0x50, 0x3e, 0xf3, 0xf1, 0x4a, 0xd5, 0x0d, 0x73, 0x24, 0x0f, 0xfa, 0xfd, 0x8e, 0xd6, 0x35,
	0x50, 0x01, 0xef, 0x02, 0x8a, 0x3f, 0x76, 0xbf, 0xd7, 0x3a, 0x7d, 0x55, 0x46, 0x62, 0xfb, 0x0d,
	0x6c, 0x65, 0x27, 0x23, 0x46, 0xf0, 0x4c, 0x1e, 0x68, 0xa6, 0xa2, 0x99, 0x23, 0x53, 0xb9, 0x35,
	0x51, 0x2e, 0x9d, 0xf9, 0xca, 0x18, 0x68, 0x48, 0x68, 0x3b, 0x21, 0x53, 0xfa, 0xfe, 0x71, 0x0d,
	0xca, 0xc6, 0x50, 0x96, 0x15, 0xc3, 0x40, 0x39, 0x1a, 0x68, 0x83, 0x7e, 0xc7, 0x94, 0xdf, 0x22,
	0x01, 0x6f, 0x01, 0xa8, 0x5a, 0xcc, 0x3d, 0x8f, 0xeb, 0x50, 0xed, 0xf4, 0x2f, 0xd5, 0xeb, 0xe1,
	0x60, 0x48, 0x09, 0x55, 0x40, 0x34, 0xde, 0x0e, 0xbe, 0x43, 0x22, 0x95, 0xa8, 0x2b, 0x5d, 0x55,
	0x57, 0x64, 0x13, 0x15, 0xf1, 0x0e, 0xd4, 0x79, 0x34, 0x62, 0x05, 0xa5, 0xf6, 0xdf, 0x02, 0x40,
	0xd2, 0x2c, 0x5c, 0x86, 0x82, 0xa1, 0x50, 0x66, 0x00, 0xa5, 0xae, 0x12, 0x39, 0x83, 0x61, 0xeb,
	0xdb, 0x4e, 0x4f, 0xed, 0x76, 0x4c, 0x65, 0x64, 0x98, 0x1d, 0xdd, 0x44, 0x79, 0xca, 0x3c, 0xce,
	0x29, 0x5a, 0x37, 0x74, 0x21, 0xa9, 0x8a, 0x68, 0x8b, 0xf8, 0x39, 0x6c, 0xc7, 0xd9, 0xab, 0x8e,
	0xda, 0x53, 0xba, 0xa8, 0x18, 0xca, 0xee, 0xf7, 0x55, 0x33, 0x82, 0x2b, 0x51, 0x41, 0x51, 0x86,
	0x82, 0x95, 0xa9, 0x20, 0x63, 0x78, 0x69, 0xc8, 0xba, 0x7a, 0xa9, 0xa0, 0x0a, 0x45, 0x89, 0xc3,
	0x51, 0x7f, 0xd8, 0x33, 0x55, 0x54, 0xc5, 0x7b, 0xb0, 0x93, 0x24, 0x75, 0xe5, 0x9b, 0xa1, 0x62,
	0x98, 0x08, 0xf0, 0x36, 0xd4, 0xa8, 0x97, 0x23, 0x79, 0xa0, 0x5d, 0xa9, 0xd7, 0xa8, 0xd6, 0xfe,
	0x14, 0xea, 0x99, 0x77, 0x43, 0xad, 0x8c, 0xba, 0x87, 0x72, 0xd4, 0xab, 0xd0, 0xfa, 0xf3, 0x4b,
	0x10, 0xa9, 0xf5, 0xf8, 0x02, 0x4a, 0x5d, 0x97, 0xad, 0x0e, 0xd6, 0xc7, 0x72, 0x74, 0x2d, 0x9b,
	0x7b, 0x0f, 0x3f, 0x2c, 0xec, 0x95, 0x94, 0x3b, 0xff, 0x53, 0x80, 0x0a, 0x9f, 0x9b, 0xf8, 0x0a,
	0xa0, 0xeb, 0xc6, 0xd1, 0x51, 0x7a, 0xcf, 0xda, 0xbf, 0xa5, 0xe6, 0xe1, 0xe6, 0x8f, 0x0c, 0x14,
	0xdf, 0x02, 0x4a, 0x70, 0xc2, 0xc9, 0x88, 0x3f, 0xd9, 0xb4, 0x21, 0x33, 0x7e, 0x9b, 0x1f, 0x3f,
	0x56, 0x12, 0xd2, 0xfd, 0x01, 0x20, 0x99, 0xb6, 0xb8, 0x07, 0xcf, 0x42, 0xe1, 0x51, 0x7c, 0xb2,
	0xae, 0x32, 0x8b, 0x7f, 0xf4, 0xa1, 0xcf, 0x21, 0xb6, 0x06, 0xa5, 0xf0, 0x62, 0xe1, 0x2e, 0x54,
	0xba, 0x6e, 0xb4, 0x3e, 0x7c, 0x38, 0x25, 0x38, 0xde, 0xc1, 0xa6, 0x4f, 0x0c, 0xab, 0x25, 0xbc,
	0x62, 0xed, 0xa1, 0x4f, 0x1c, 0x5f, 0x44, 0x7f, 0x33, 0xe5, 0xa9, 0x99, 0x91, 0x6d, 0x4e, 0x3c,
	0x15, 0xa4, 0xdc, 0x2b, 0xe1, 0xae, 0xc4, 0x7e, 0x95, 0xbe, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x36, 0xff, 0x32, 0x13, 0xa9, 0x0a, 0x00, 0x00,
}
